### ISSUE TITLE
Deployment behind firewall

### ISSUE THREAD

**Issue by arj03** [newrelic/centurion#115]
Hi

Centurion looks really well designed, but am I correct in assuming that it doesn't allow one to deploy to machines behind firewalls?

**Comment by relistan** [comment]
Hi @arj03 thanks. :) I have never tried it personally, but because we rely on Excon for much of the API work, a lot of it will probably work if you set `http_proxy` and `https_proxy` environment variables. Check out the last section here: https://github.com/excon/excon#proxy-support

It looks like the Docker CLI which we also use for certain operations under the covers will also support proxying: http://robwin.blogspot.com/2014/04/running-docker-on-centos-behind-proxy.html

Give that a shot and please report back if it works!

**Comment by arj03** [comment]
Hi 

Thanks for your reply.

I'm a little unsure as to how the deploy works exactly. It seems like one specifies the hostnames / ips of the machines that one deploys to, so it looks as if you ssh into them and update them? Or how do you trigger them to start the update?

**Comment by kremso** [comment]
Hi @arj03, we were deploying to machines behind a firewall, but abandoned that pretty quickly. Centurion communicates with docker deamon (mostly) via its [API](https://docs.docker.com/reference/api/docker_remote_api_v1.12/), so we opened that port on firewall and set up a TLS authentication to maintain security. That was a major pain point, since we had to generate and maintain additional certificates and distribute them to servers. We even had this automated, but it was simply not worth it. In the end, we opened an additional machine within the unfirewalled private network and just deploy from there. So the steps are: 1. ssh to the deploy machine, 2. pull fresh scripts, 3. run centurion.

**Comment by arj03** [comment]
Thanks for the explanation.

The problem is we are thinking of deploying to thousands of machines in vastly different networks, so opening a port up is not something we just do. One way around it is to start an ssh tunnel for when we update, but then that has to be handled seperately and integrated into the deploy process.

**Comment by relistan** [comment]
How would you envision this should work? I'm not sure I understand how you would want this to work. In order to deploy you'll need to talk to the servers, somehow, so a deployment/jump host as @kremso suggests is about the easiest way. You'll need to have some way to communicate through the firewall, obviously.

**Comment by arj03** [comment]
Well, I was thinking something along the lines of a daemon running on all the machines, that we push updates to. They can do this over standing https meaning that it should work just about anywhere.

**Comment by relistan** [comment]
@arj03 Docker uses https when you have TLS enabled. Centurion supports TLS thanks to @zedtux so I think it already does what you want. Check out the TLS settings in the `README`.
