### ISSUE TITLE
I want to add my own rake tasks. Not sure where to put db.rake file

### ISSUE THREAD

**Issue by benpillet** [newrelic/centurion#169]
First off, thanks for building this.  I'm looking forward to seeing it running in our system.

I want to add a task/action to run a rails db:migrate task within the first_server container.  I'm not sure where to put it though.

**Comment by relistan** [comment]
The easiest thing to do is to put it in your config for your project. Since that rake file will already be loaded, you can just add tasks there (even in their own namespace if you like), and they will be available. If you prefer to have them in a separate rake file then you can simply `require` them in your config. The config and all included files are loaded before the task is invoked.
